// Generated by scripts/generate-tincta-brand.mjs. Edit the canonical geometry, not this file.
type TinctaLogoProps = { className?: string; title?: string };

export function TinctaWordmark({ className, title = "Tincta" }: TinctaLogoProps) {
  return (
    <svg className={className} width="135" height="42" viewBox="0 0 270 84" role={title ? "img" : undefined} aria-label={title || undefined} aria-hidden={title ? undefined : true} focusable="false" data-tincta-logo="wordmark">
      {title && <title>{title}</title>}
      <g transform="translate(8 8)" fill="none" stroke="currentColor" strokeWidth={8} strokeLinecap="butt" strokeLinejoin="round">
      <path d="M15 5V53Q15 65 29 65H34M2 25H35M51 25V66M73 66V25M73 41C73 20 111 20 111 42V66M159 33C143 18 125 27 125 46C125 65 144 75 160 60M179 5V53Q179 65 193 65H198M166 25H199M250 35C235 15 210 24 210 46C210 68 236 76 250 57M250 25V66" />
      <path d="M51 5V13" />
      </g>
    </svg>
  );
}

export function TinctaMark({ className, title = "Tincta" }: TinctaLogoProps) {
  return (
    <svg className={className} width="32" height="32" viewBox="0 0 100 100" role={title ? "img" : undefined} aria-label={title || undefined} aria-hidden={title ? undefined : true} focusable="false" data-tincta-logo="mark">
      {title && <title>{title}</title>}
      <path fill="currentColor" d="M35 9H52V31H82V47H52V69Q52 77 60 77H78V93H58Q35 93 35 69V47H16V31H35Z" />
    </svg>
  );
}
